"""Value function: linear composition of factors for action scoring."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from api.models import GameState, Position, Plantation, Construction, TerraformCell
from strategy.brain.utils import adjacent, chebyshev, manhattan, is_reinforced
from strategy.brain.spatial import InfluenceMap


@dataclass
class ActionCandidate:
    """A potential action generated by a plantation."""
    action_type: Literal["build", "repair", "sabotage", "attack_beaver", "idle"]
    author: Position
    target: Position
    exit_point: Position | None = None
    base_score: float = 0.0
    utility: float = 0.0
    priority: bool = False  # critical override (HQ repair, isolation fix)
    target_cap: int = 1  # max builders for this target


class ValueFunction:
    """Scores actions based on economic, topological, and risk factors."""

    # Weights
    W_ECON_SPEED = 1.0
    W_REINFORCED = 1.2
    W_CONNECTIVITY = 1.5
    W_BRIDGE = 1.0
    W_BEAVER_RISK = -1.0
    W_STORM_RISK = -0.8
    W_TERRAFORM_DEATH = -2.0
    W_CONTESTED = -0.5
    W_KILL = 0.6

    def evaluate(
        self,
        action: ActionCandidate,
        state: GameState,
        spatial: InfluenceMap,
        own_positions: set[Position],
        hq: Plantation | None,
        terraform_by_pos: dict[Position, TerraformCell],
    ) -> float:
        if action.action_type == "idle":
            return 0.0

        score = 0.0
        target = action.target

        # === Economic ===
        cell_value = spatial.value_heatmap.get(target, 0.0)
        score += cell_value * self.W_ECON_SPEED
        if is_reinforced(target):
            score += 150.0 * self.W_REINFORCED

        # === Topological ===
        if hq is not None:
            dist_hq = manhattan(target, hq.position)
            # Connectivity to HQ: closer is better for repairs, moderate for builds
            if action.action_type == "repair":
                score += max(0, 20 - dist_hq) * self.W_CONNECTIVITY * 2
            elif action.action_type == "build":
                score += max(0, 15 - dist_hq) * self.W_CONNECTIVITY

        # Bridge node value: cells that connect clusters
        if action.action_type == "build":
            own_neighbors = sum(1 for n in adjacent(target) if n in own_positions)
            if own_neighbors >= 2:
                score += 40.0 * self.W_BRIDGE

        # === Risk ===
        threat = spatial.threat_heatmap.get(target, 0.0)
        score += threat * self.W_BEAVER_RISK

        # Terraform death risk: critical for HQ and HQ neighbors
        if hq is not None:
            if target == hq.position and action.action_type == "repair":
                # repairing HQ is always high value, but death risk adds urgency
                cell = terraform_by_pos.get(hq.position)
                if cell is not None:
                    score += (cell.terraformation_progress / 100.0) * 200.0 * self.W_TERRAFORM_DEATH
            elif target in adjacent(hq.position) and action.action_type in ("build", "repair"):
                cell = terraform_by_pos.get(target)
                if cell is not None:
                    # high progress on escape cell is very bad
                    risk = (cell.terraformation_progress / 100.0) ** 2
                    score += risk * 100.0 * self.W_TERRAFORM_DEATH

        # Contested: if enemy plant or construction nearby
        if action.action_type == "build":
            enemy_near = any(
                chebyshev(target, ep.position) <= 2
                for ep in state.enemy_plantations
            )
            if enemy_near:
                score += 30.0 * self.W_CONTESTED

        # === Kill probability (sabotage) ===
        if action.action_type == "sabotage":
            score += 50.0 * self.W_KILL

        # === HQ-specific head grooming bonus ===
        if hq is not None and target in adjacent(hq.position):
            if action.action_type == "build":
                # Building escape routes for HQ
                cell = terraform_by_pos.get(target)
                progress = cell.terraformation_progress if cell else 0
                if progress < 40:
                    score += 200.0  # head grooming bonus
            elif action.action_type == "repair":
                score += 80.0

        return score

    def head_grooming_bonus(
        self,
        target: Position,
        head_plan: list[Position],
        action_type: str,
    ) -> float:
        """Additional bonus for actions that support the planned HQ head."""
        if not head_plan:
            return 0.0
        bonus = 0.0
        # Proximity to planned HQ positions
        for planned_hq in head_plan[:2]:  # next 2 planned positions
            dist = manhattan(target, planned_hq)
            if dist <= 1 and action_type == "build":
                bonus += 260.0
            elif dist <= 2 and action_type in ("build", "repair"):
                bonus += 120.0
        return bonus
